---
# Set up Compiz configuration.
#
# @see https://wiki.archlinux.org/index.php/Compiz_configuration#Configuration_backends
# @todo: use named profile instead.

- name: Make sure Compiz config directory structure exists.
  file:
    path: "{{ config_home_dir }}/{{ item.user }}/.config/compiz-1/compizconfig"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    state: directory
    recurse: yes
  with_items: "{{ config_users }}"
  when: "{{ config_compiz_use_ini_backend }}"

- name: Set Compiz to use the ini backend.
  lineinfile:
    dest: "{{ config_home_dir }}/{{ item.user }}/.config/compiz-1/compizconfig/config"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    create: yes
    regexp: "^backend = "
    line: "backend = ini"
  with_items: "{{ config_users }}"
  when: "{{ config_compiz_use_ini_backend }}"

- name: Symlink our compiz config file into place.
  file:
    src: "{{ config_home_dir }}/{{ item.user }}/{{ config_config_dir_name }}/{{ config_dotfiles_dir_name }}/{{ config_compiz_config_file_name }}"
    dest: "{{ config_home_dir }}/{{ item.user }}/.config/compiz-1/compizconfig/Default.ini"
    state: link
    force: yes
  with_items: "{{ config_users }}"
  when: "{{ config_compiz_use_ini_backend }}"
